version: "3"
services:
  mvdwfapps:
    container_name: mvdwfapps
    restart: always
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: ['9040:9040']
    env_file:
      - .env